version: '3'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: 'debuggers-db'
    env_file:
      - db.env
  app:
    build: ./
    container_name: 'debuggers-backend'
    ports:
      - "8080:8080"
    env_file:
      - docker.env