facebook:
  client-id: 639777021199239
  client-secret: 93d125256e4cbaa74630c32b87de2899

jwt:
  secret: somesecretsomesecretsomesecretsomesecretsomesecretsomesecretsomesecretsomesecretsomesecretsomesecret