facebook:
  client-id: ${FACEBOOK_CLIENT_ID}
  client-secret: ${FACEBOOK_CLIENT_SECRET}

jwt:
  secret: somesecretsomesecretsomesecretsomesecretsomesecretsomesecretsomesecretsomesecretsomesecretsomesecret