facebook:
  client-id: ${FACEBOOK_CLIENT_ID}
  client-secret: ${FACEBOOK_CLIENT_SECRET}
  native_user:
    coordinator:
      email: ${COORDINATOR_EMAIL}
    interviewer:
      email: ${INTERVIEWER_EMAIL}

jwt:
  secret: ${JWT_SECRET}