-- test data
INSERT INTO USERS(ID, EMAIL, ROLE)
    VALUES (NEXTVAL('USER_SEQUENCE'), 'interviewer@test.do', 'INTERVIEWER');
INSERT INTO USERS(ID, EMAIL, ROLE)
    VALUES (NEXTVAL('USER_SEQUENCE'), 'candidate@test.do', 'CANDIDATE');