CREATE SEQUENCE IF NOT EXISTS USER_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS BOOKING_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS INTERVIEWER_SLOT_SEQUENCE;
CREATE SEQUENCE IF NOT EXISTS CANDIDATE_SLOT_SEQUENCE;
CREATE INDEX idx_users_email on USERS (EMAIL);
CREATE INDEX idx_users_role on USERS (ROLE);
CREATE INDEX idx_cand_slot_date on CANDIDATE_TIME_SLOT (DATE);
CREATE INDEX idx_interv_slot_weeknum on INTERVIEWER_TIME_SLOT (WEEK_NUM);
-- CREATE INDEX on BOOKING(CANDIDATE_EMAIL);